---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Viewlift Acadia Stack Version 1'
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
    - Label:
        default: 'VPC Parameters'
      Parameters:
      - ClassB
      - VPCName
      - Environment
      - ApiId
      - KmsKey
Parameters:
  ClassB:
    Description: 'Class B of VPC (10.XXX.0.0/16)'
    Type: Number
    Default: 100
    ConstraintDescription: 'Must be in the range [0-255]'
    MinValue: 0
    MaxValue: 255
  VPCName:
    Description: 'Identifiable name for VPC'
    Type: String
    Default: 'Viewlift Acadia VPC'
  Environment:
    Description: 'Environment Identifier'
    Type: String
    Default: 'prod'
    AllowedValues:
    - develop
    - release
    - prod
  ApiId:
    Description: 'API Gateway Identifier'
    Type: String
    Default: '3cutwjvgl2'
  KmsKey:
    Description: 'Last part of KMS Key Arn'
    Type: String
    Default: '2b00e907-b58e-48da-905e-e408d0e81c11'  
Mappings:
  EnvironmentMap:
    develop:
      tablePrefix: 'DEVELOP'
    release:
      tablePrefix: 'RELEASE'
    prod:
      tablePrefix: 'PROD'
  RegionMap:
    us-east-1:
      bucketName: 'viewlift-acadia'
    us-west-2:
      bucketName: 'or-viewlift-acadia'
Resources:
  Network:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/viewlift-acadia/stack/vpc-${Environment}.yaml'
      TimeoutInMinutes: 90
      Parameters:
        ClassB: !Sub ${ClassB}
        VPCName: !Sub '${VPCName}'
  ContentServiceTables:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://s3.amazonaws.com/viewlift-acadia/services/content-service/tables.yaml'
      TimeoutInMinutes: 90
      Parameters:
        Environment: !Ref Environment
        TablePrefix: !FindInMap [ EnvironmentMap, !Ref "Environment", tablePrefix ]

Outputs:
  VPCID:
    Value: !GetAtt 'Network.Outputs.VpcId'
  DefaultSecurityGroup:
    Value: !GetAtt 'Network.Outputs.DefaultSecurityGroup'
  ContentMetadataTableStream:
    Value: !GetAtt 'ContentServiceTables.Outputs.ContentMetadataTableStream'
    Export:
      Name: !Sub '${AWS::StackName}-ContentMetadataStreamArn'
  SiteConfigTableStream:
    Value: !GetAtt 'ContentServiceTables.Outputs.SiteConfigTableStream'
    Export:
      Name: !Sub '${AWS::StackName}-SiteConfigStreamArn'
  VideoWatchHistoryTableStream:
    Value: !GetAtt 'ContentServiceTables.Outputs.VideoWatchHistoryTableStream'
    Export:
      Name: !Sub '${AWS::StackName}-VideoWatchHistoryStreamArn'
